def dibujar_ahorcado(intentos):
    if intentos == 6:
        print("  ________")
        print(" |        |")
        print(" |")
        print(" |")
        print(" |")
        print(" |")
        print("_|_________\n")
    elif intentos == 5:
        print("  ________")
        print(" |        |")
        print(" |        O")
        print(" |")
        print(" |")
        print(" |")
        print("_|_________\n")
    elif intentos == 4:
        print("  ________")
        print(" |        |")
        print(" |        O")
        print(" |        |")
        print(" |")
        print(" |")
        print("_|_________\n")
    elif intentos == 3:
        print("  ________")
        print(" |        |")
        print(" |        O")
        print(" |       /|")
        print(" |")
        print(" |")
        print("_|_________\n")
    elif intentos == 2:
        print("  ________")
        print(" |        |")
        print(" |        O")
        print(" |       /|\\")
        print(" |")
        print(" |")
        print("_|_________\n")
    elif intentos == 1:
        print("  ________")
        print(" |        |")
        print(" |        O")
        print(" |       /|\\")
        print(" |       /")
        print(" |")
        print("_|_________\n")
    else:
        print("  ________")
        print(" |        |")
        print(" |        O")
        print(" |       /|\\")
        print(" |       / \\")
        print(" |")
        print("_|_________\n")